version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Optional, for testing
    environment:
      - DATABASE_URL=mysql://u3079686_sigma:yoursocialsecurityisexpiredpleaseenteritmanually@mysql:3306/u3079686_dev
      - JWT_SECRET=default-secret-key-please-change-me
      - PORT=3000
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=u3079686_dev
      - MYSQL_USER=u3079686_sigma
      - MYSQL_PASSWORD=yoursocialsecurityisexpiredpleaseenteritmanually
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./var/www/html:/var/www/html
      - ./certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: